### ISSUE TITLE
Alesia's new issue

### ISSUE THREAD

**Issue by alesiahallmark** [gremau/NMEG_fluxproc_testing#4]
I have some issues with this code.

**Comment by gremau** [comment]
Were you talking about the MCon 2012 Ameriflux file? Is the issue that the datalogger timestamps look insane? Like this?

![examplefig_1](https://cloud.githubusercontent.com/assets/1557987/7118913/69404b10-e1bf-11e4-8571-863f7a9eedd0.png)

**Comment by gremau** [comment]
Made some progress fixing that issue. Does this look better?

![examplefig_2](https://cloud.githubusercontent.com/assets/1557987/7118954/ba6166a0-e1bf-11e4-917a-37dde16f4822.png)

**Comment by alesiahallmark** [comment]
That does look better, Greg!

**Comment by gremau** [comment]
Great! closing this issue then.
